<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Nimrod Language. By Leonardo Cecchi &lt;leonardoce@interfree.it&gt;</string>
	<key>fileTypes</key>
	<array>
		<string>nim</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*([a-zA-Z_]\w*)\s*(\(.*\)\s*)?$</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*\s*$</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Nimrod</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(proc|iterator|method|template|macro)\b</string>
			<key>name</key>
			<string>meta.function.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.apostrophe.nimrod</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>discard """</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.nimrod</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.nimrod</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.apostrophe.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(block|break|case|continue|discard|do|elif|else|end|except|try|finally|for|from|if|method|object|type|return|when|while|with|without|import|export|include|var|let|const|raise|echo|yield|assert|ref|ptr)\b</string>
			<key>name</key>
			<string>keyword.control.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(not|xor|shl|shr|div|mod|in|notin|is|isnot|of|and|or)\b|(=|\+|-|\*|/|&lt;|&gt;|@|\$|~|&amp;|%|!|\?|\^|\.|:|\\)+)</string>
			<key>name</key>
			<string>keyword.operator.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addr|atomic|const|enum|static|tuple|var|with|without|char|bool|int|int8|int16|int32|int64|uint|uint8|uint16|uint32|uint64|float|float32|float64|string|typedesc|seq|stmt|expr)\b</string>
			<key>name</key>
			<string>storage.type.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\*)</string>
			<key>name</key>
			<string>storage.modifier.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(nil|true|false|[0-9]+)\b)</string>
			<key>name</key>
			<string>constant.language.nimrod</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nimrod</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nimrod</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nimrod</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nimrod</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nimrod</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nimrod</string>
		</dict>
        <dict>
            <key>match</key>
            <string>'(\\\d{1,3}|\\?[^\n]?)'</string>
            <key>name</key>
            <string>string.quoted.single.nimrod</string>
        </dict>
	</array>
	<key>scopeName</key>
	<string>source.nimrod</string>
	<key>uuid</key>
	<string>4060da00-dca1-11e1-9b23-0800200c9a66</string>
</dict>
</plist>
